trigger:
- main  # Trigger pipeline when changes are pushed to the main branch

stages:
# Stage 1: Build and Artifact Management
- stage: Build
  displayName: Build and Artifact Management
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'  # Ubuntu-based image for the agent
    steps:
    # Task 1: List contents of the System Default Working Directory
    - bash: echo "Contents in System Default Working Directory"; ls -R $(System.DefaultWorkingDirectory)
    
    # Task 2: List contents of Build Artifact Staging Directory before copying files
    - bash: echo "Before copying to Build Artifact Directory"; ls -R $(Build.ArtifactStagingDirectory)
    
    # Task 3: Copy files (Copy files from source folder to target folder)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/terraform-manifests'  # Source folder with Terraform configuration
        Contents: '**'  # Copy all contents recursively
        TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Target folder for artifacts
        OverWrite: true  # Allow overwriting of existing files
        
    # Task 4: List files from Build Artifact Staging Directory after copy
    - bash: echo "After copying to Build Artifact Directory"; ls -R $(Build.ArtifactStagingDirectory)
    
    # Task 5: Publish build artifacts to Azure Pipelines
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Path to the artifact directory
        ArtifactName: 'terraform-manifests'  # Artifact name
        publishLocation: 'Container'  # Publish to the default Azure container

